name: Cross-Compile Binaries

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # 1) Linux host dependencies (GTK/WebKit/etc)
      - name: Install Linux native deps
        run: |
          sudo apt-get update
          sudo apt install -y \
            build-essential pkg-config curl wget file \
            libssl-dev \
            libglib2.0-dev \
            libgtk-3-dev libgdk-pixbuf2.0-dev libpango1.0-dev libcairo2-dev \
            libayatana-appindicator3-dev librsvg2-dev libsecret-1-dev \
            libwebkit2gtk-4.1-dev libjavascriptcoregtk-4.1-dev \
            libsoup-3.0-dev \
            libasound2-dev \
            libxdo-dev \
            webkit2gtk-driver

      # 2) Build the React front end
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install & build front end
        run: |
          npm ci
          npm run build

      # 3) Rust + cross‑compile targets
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy, rustfmt
      - name: Add Rust target
        run: rustup target add ${{ matrix.target }}

      # 4) MinGW for Windows GNU on Ubuntu
      - name: Install MinGW for Windows
        if: matrix.target == 'x86_64-pc-windows-gnu'
        run: sudo apt-get update && sudo apt-get install -y mingw-w64

      # 5) Build Tauri backend (both targets)
      - name: Build Tauri for ${{ matrix.target }}
        run: |
          cd src-tauri
          ORT_STRATEGY=system \
          ORT_LIB_LOCATION=/usr/local/lib/onnxruntime \
          cargo build --release --target ${{ matrix.target }}

      # 6) Upload compiled bundles
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: src-tauri/target/${{ matrix.target }}/release/bundle/
