name: Cross-Compile Binaries

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            runner: ubuntu-latest
          - target: x86_64-pc-windows-msvc
            runner: windows-latest

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy, rustfmt
          targets: ${{ matrix.target }}

      - name: (Windows) Install ONNX Runtime
        if: matrix.runner == 'windows-latest'
        run: |
          choco install onnxruntime

      - name: Build Tauri backend
        run: |
          cd src-tauri
          ORT_STRATEGY=system \
          ORT_LIB_LOCATION=/usr/local/lib/onnxruntime \
          cargo build --release --target ${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: src-tauri/target/${{ matrix.target }}/release/bundle/
