name: Cross-Compile Binaries

on:
  push:
    tags:
      - 'v*.*.*'    # e.g. v0.1.0, v1.2.3

  workflow_dispatch:          # <-- enables manual runs :contentReference[oaicite:0]{index=0}

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cross (for cross-compilation)
        run: cargo install cross

      - name: Add musl & Windows targets
        run: |
          rustup target add x86_64-unknown-linux-musl
          rustup target add x86_64-pc-windows-gnu

      - name: Build Linux (MUSL) and Windows (GNU)
        run: |
          cross build --release --target x86_64-unknown-linux-musl
          cross build --release --target x86_64-pc-windows-gnu

      - name: list build outputs
        run: |
          ls -l target/x86_64-unknown-linux-musl/release
          ls -l target/x86_64-pc-windows-gnu/release

      - name: Upload backend artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-binaries
          path: |
            target/x86_64-unknown-linux-musl/release/jarvis-rust-backend
            target/x86_64-pc-windows-gnu/release/jarvis-rust-backend.exe
