name: Release

on:
  push:
    branches: [ main ]

jobs:
  semantic_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: { node-version: 22 }
      - run: npm ci
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

  cross_compile:
    needs: semantic_release           # wait for semantic-release to succeed :contentReference[oaicite:9]{index=9}
    uses: ./.github/workflows/cross-compile.yml  # call reusable workflow :contentReference[oaicite:10]{index=10}

  attach_artifacts:
    needs: cross_compile
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts

      - name: Attach to GitHub Release
        uses: softprops/[email protected]
        with:
          tag_name: ${{ github.ref_name }}
          files: artifacts/**/*.{AppImage,rpm,deb,exe}
