name: Release

on:
  push:
    branches: [ master ]

jobs:
  semantic_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - run: npm ci
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

  cross_compile:
    needs: semantic_release
    uses: ./.github/workflows/cross-compile.yml

  attach_artifacts:
    needs: cross_compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Attach to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            artifacts/**/*.rpm
            artifacts/**/*.deb
            artifacts/**/*.exe